[package]
name = "lemonbar_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio={version='1.26.0', features=["full"]}
chrono="0.4.24"
battery="0.7.8"
volume="0.3.0"
